name: CMake

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: sfml
          run: sudo apt-get update && sudo apt-get install libsfml-dev

        - name: Configure CMake
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

        - name: Build
        # Build your program with the given configuration
          run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

        - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
            name: window
            path: ${{github.workspace}}/build/libengine.a

        - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
          run: ctest -C ${{env.BUILD_TYPE}}
